version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: baza
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: baza
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
