services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DBPASS:?db password not set}
      POSTGRES_USER: ${DBUSER:?db user not set}
      POSTGRES_DB: ${DBNAME:?db name not set}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER} -d ${DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres-net
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - postgres-net
  web-app:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres-net
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--reload", "app:f_app"]
volumes:
  postgres-data:
networks:
  postgres-net:
  